Repository opencrvs/opencrvs-countryconfig, pull requests merged in 2024-08, with the labels that each got.

#224 fix: remove overshadowing rect
  src/data-seeding/certificates/source/Farajaland-birth-certificate-v2.svg
  src/data-seeding/certificates/source/Farajaland-death-certificate-v2.svg
  src/data-seeding/certificates/source/Farajaland-marriage-certificate-v2.svg
Labels: ✅ Ready for merging

#119 chore: remove unused props
  src/form/types/types.ts
Labels: ✅ Ready for merging

#159 fix: add output for reset job
  .github/workflows/clear-environment.yml
Labels: ✅ Ready for merging

#229 fix(alerts): use mount point filters for disk space alerts
  CHANGELOG.md
  infrastructure/monitoring/kibana/config.ndjson
Labels: 💅 Waiting for review

#212 chore: rename application config file
  src/api/application/application-config.ts
  src/api/application/handler.ts
  src/index.ts
  src/translations/client.csv
Labels: ✅ Ready for merging

#233 docs: update changelog(#6924)
  CHANGELOG.md
Labels: 💅 Waiting for review

#219 Fix/custom ssh port config
  infrastructure/server-setup/inventory/qa.yml
  infrastructure/server-setup/tasks/ufw.yml
Labels: ✅ Ready for merging

#239 ignore unavailable indices upon delete
  infrastructure/elasticsearch/setup-elastalert-indices.sh
Labels: ✅ Ready for merging

#241 Serve client manifest and icons from country-config
  src/client-static/images/icons/icon-128x128.png
  src/client-static/images/icons/icon-144x144.png
  src/client-static/images/icons/icon-152x152.png
  src/client-static/images/icons/icon-196x196.png
  src/client-static/images/icons/icon-256x256.png
  src/client-static/images/icons/icon-512x512.png
  src/client-static/images/icons/icon-72x72.png
  src/client-static/images/logo-90x90.svg
  src/client-static/manifest.json
  src/index.ts
Labels: 🔧 Waiting for fixes

#218 Update CHANGELOG
  CHANGELOG.md
Labels: 🔧 Waiting for fixes

#245 fix(releasing): Explicitly specify from which branch the release tag should be created from OCRVS-7369
  .github/workflows/publish-release.yml
  CHANGELOG.md
Labels: ✅ Ready for merging

#244 OCRVS-7404 Fix: Remove unnecessary dividers in the declaration forms
  CHANGELOG.md
  src/form/addresses/index.ts
  src/form/birth/index.ts
  src/form/death/index.ts
  src/form/marriage/index.ts
Labels: 💅 Waiting for review

#247 feat(environment-creator): only allow using tokens in environment creator that do not expire [OCRVS-7367]
  .github/workflows/get-secret-from-environment.yml
  CHANGELOG.md
Labels: ✅ Ready for merging

#250 chore: protect individual certificate endpoint with token
  CHANGELOG.md
  src/api/certificates/handler.ts
  src/api/certificates/source/Farajaland-birth-certificate-v2.svg
  src/api/certificates/source/Farajaland-death-certificate-v2.svg
  src/api/certificates/source/Farajaland-marriage-certificate-v2.svg
  src/api/certificates/source/test/UsingAddressHandlebars.svg
  src/api/certificates/source/test/UsingSignatureHandlebars.svg
  src/data-seeding/certificates/handler.ts
  src/index.ts
Labels: ✅ Ready for merging
