Repository opencrvs/opencrvs-countryconfig, pull requests merged in 2024-06, with the labels that each got.

#124 Fix Correct item names in update modal for marriage declaration
  CHANGELOG.md
  src/form/marriage/index.ts
  src/translations/client.csv
Labels: documentation

#115 don't require regLastLocation in Postman Event Notification
  postman/Event Notification.postman_collection.json
Labels: on hold

#116 fix: simplify hierarchy now that it can be queried through graphql
  src/form/index.ts
  src/utils/users.ts
Labels: on hold

#134 ocrvs-7080: International Postal Code field Added for the place of delivery in the child's details section.
  CHANGELOG.md
  src/utils/address-utils.ts
Labels: Waiting for review

#140 Trivvy scan
  .github/workflows/publish-to-dockerhub.yml
  .trivyignore.yaml
  trivy.yml
Labels: Waiting for review

#139 chore(ocrvs-7138): update dashboard query with the recent correction flow changes
  src/api/dashboards/queries.ts
Labels: Waiting for review

#150 fix: update certified at message id for verify certificate
  src/translations/client.csv
Labels: Waiting for review

#165 Enforce token for seeding roles and users
  src/index.ts
Labels: Waiting for review

#164 fix: sms not being sent
  src/api/notification/sms-service.ts
Labels: Waiting for review
