Repository opencrvs/opencrvs-countryconfig, pull requests merged in 2025-08, with the labels that each got.

#855 Drop ping logs which has 200 status code(OCRS-9722)
  infrastructure/monitoring/logstash/logstash.conf
Labels: Stale

#955 initial schema for Metabase
  package.json
  src/analytics/analytics.ts
  src/analytics/postgres.ts
  src/analytics/setup-database.ts
  src/api/registration/index.ts
  src/constants.ts
  src/environment.ts
  src/index.ts
  yarn.lock
Labels: 🚧 work in progress

#941 Trigger notification for events
  package.json
  src/api/custom-event/handler.ts
  src/api/notification/__snapshots__/notification.informant.email.test.ts.snap
  src/api/notification/__snapshots__/notification.informant.sms.test.ts.snap
  src/api/notification/email-service.ts
  src/api/notification/email-templates/index.ts
  src/api/notification/email-templates/other/2-factor-authentication.html
  src/api/notification/email-templates/other/onboarding-invite.html
  src/api/notification/email-templates/other/password-reset-by-system-admin.html
  src/api/notification/email-templates/other/password-reset.html
  src/api/notification/handler.ts
  src/api/notification/informantNotification.ts
  src/api/notification/notification.informant.email.test.ts
  src/api/notification/notification.informant.sms.test.ts
  src/api/notification/notification.user.email.test.ts
  src/api/notification/notification.user.sms.test.ts
  src/api/notification/sms-service.ts
  src/api/notification/testData.ts
  src/api/registration/index.ts
  src/index.ts
  src/translations/client.csv
  src/translations/notification.csv
  yarn.lock
Labels: 💅 Waiting for review
