Repository opencrvs/opencrvs-countryconfig, pull requests merged in 2025-07, with the labels that each got.

#840 [OCRVS-9837] Fix certificate UI issues
  src/api/certificates/source/birth-certificate.svg
  src/api/certificates/source/death-certificate.svg
  src/api/certificates/source/marriage-certificate.svg
Labels: 💅 Waiting for review

#804 fix: remove draft status from advance search config
  src/form/EventMetadataSearchOptions.ts
Labels: 💅 Waiting for review, Phase 2 (Events v2)

#845 feat: backup postgres
  .github/workflows/provision.yml
  infrastructure/backups/backup.sh
  infrastructure/backups/download.sh
  infrastructure/backups/restore.sh
  infrastructure/server-setup/tasks/data-partition.yml
Labels: on hold, 🚧 work in progress
